sudo: required
language: java

services:
  - docker

before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
